apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: papaia
spec:
  selector:
    app-component: web-app
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: papaia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpms
      app-component: web-app
  template:
    metadata:
      labels:
        app: cpms
        app-component: web-app
    spec:
      containers:
        - name: web-app
          image: ${REPO}/${IMAGE_NAME}:$ITEM_VERSION_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: "config"
              mountPath: "/public/configFE.js"
              subPath: "configFE.js"
      volumes:
        - name: "config"
          configMap:
            name: "staging-totem-config"