openapi: 3.0.2
info:
  title: eMSP-BookingManagementService
  version: 1.0.0
  description: A brand new API with no content.  Go nuts!
servers:
  - url: 'http://employee-service'
    description: ''
tags:
  - name: employee
paths:
  /employee/login:
    post:
      summary: Employee login
      operationId: Employee login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      tags:
        - employee
  '/employee/{employeeId}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: employeeId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
      operationId: get-employee
      tags:
        - employee
components:
  schemas:
    Error:
      title: Root Type for Error
      description: ''
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          format: int32
          type: integer
          readOnly: true
        detail:
          type: string
        instance:
          type: string
      example:
        type: /errors/overlapping-booking-request
        title: Overlapping booking request
        status: 409
        detail: The requested booking timeframe overlaps with another planned booking.
        instance: /booking
    SignupRequest:
      title: SignupRequest
      x-stoplight:
        id: zy4sxgjxqz1t2
      type: object
      required:
        - name
        - surname
        - emailAddress
        - password
      properties:
        name:
          type: string
        surname:
          type: string
        emailAddress:
          type: string
        password:
          type: string
      description: ''
    Employee:
      title: Employee
      x-stoplight:
        id: 0610a4afd558b
      type: object
      properties:
        employeeId:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        emailAddress:
          type: string
        token:
          type: string
      required:
        - employeeId
        - name
        - surname
        - emailAddress
        - token
    LoginRequest:
      title: LoginRequest
      x-stoplight:
        id: ccwdsnalwxh7m
      type: object
      properties:
        emailAddress:
          type: string
        password:
          type: string
  responses:
    ErrorResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: ''
  securitySchemes:
    Authenticated:
      scheme: bearer
      type: http

