openapi: 3.0.2
info:
  title: eMSP-BookingManagementService
  version: 1.0.0
  description: A brand new API with no content.  Go nuts!
paths:
  /customer:
    post:
      summary: Signup
      operationId: signup
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      tags:
        - customer
    parameters: []
  /customer/login:
    post:
      summary: Customer login
      operationId: login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      tags:
        - customer
  '/customer/{customerId}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: customerId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
      operationId: get-customer-customerId
      tags:
        - customer
components:
  schemas:
    Error:
      title: Root Type for Error
      description: ''
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          format: int32
          type: integer
          readOnly: true
        detail:
          type: string
        instance:
          type: string
      example:
        type: /errors/overlapping-booking-request
        title: Overlapping booking request
        status: 409
        detail: The requested booking timeframe overlaps with another planned booking.
        instance: /booking
    SignupRequest:
      title: SignupRequest
      x-stoplight:
        id: zy4sxgjxqz1t2
      type: object
      required:
        - name
        - surname
        - emailAddress
        - password
      properties:
        name:
          type: string
        surname:
          type: string
        emailAddress:
          type: string
        password:
          type: string
      description: ''
    Customer:
      title: Customer
      x-stoplight:
        id: 8p3v0g3l4g0xo
      type: object
      properties:
        customerId:
          type: integer
          format: int64
        name:
          type: string
        surname:
          type: string
        emailAddress:
          type: string
        token:
          type: string
      required:
        - customerId
        - name
        - surname
        - emailAddress
        - token
    LoginRequest:
      title: LoginRequest
      x-stoplight:
        id: ccwdsnalwxh7m
      type: object
      properties:
        emailAddress:
          type: string
        password:
          type: string
  responses:
    ErrorResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: ''
  securitySchemes:
    Authenticated:
      scheme: bearer
      type: http
servers:
  - url: 'http://customer-service'
    description: ''
